# Generated by Django 5.2.9 on 2026-02-02 17:04

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feriado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True)),
                ('descripcion', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Feriado',
                'verbose_name_plural': 'Feriados',
                'ordering': ['fecha'],
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legajo', models.CharField(help_text='ID único de empleado', max_length=20, unique=True)),
                ('dni', models.CharField(max_length=15, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('fecha_ingreso', models.DateField()),
                ('sector', models.CharField(choices=[('IT', 'Tecnología'), ('RRHH', 'Recursos Humanos'), ('Ventas', 'Ventas'), ('Admin', 'Administración'), ('Deposito', 'Depósito/Logística'), ('Internet', 'Internet'), ('Energía', 'Energía'), ('Mantenimiento', 'Mantenimiento')], max_length=50)),
                ('localidad', models.CharField(default='Casa Central', help_text='Sucursal o ciudad', max_length=100)),
                ('cargo', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Ej: Recibo Enero 2026', max_length=100)),
                ('archivo', models.FileField(upload_to='legajos/%Y/', validators=[core.models.validar_extension])),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='core.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='BolsaVacaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField(verbose_name='Año Correspondiente')),
                ('dias_otorgados', models.IntegerField(default=0)),
                ('dias_restantes', models.IntegerField(default=0)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bolsas', to='core.empleado')),
            ],
            options={
                'ordering': ['anio'],
                'unique_together': {('empleado', 'anio')},
            },
        ),
        migrations.CreateModel(
            name='AuditoriaSaldo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('accion', models.CharField(max_length=200)),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Licencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENFERMEDAD', 'Enfermedad'), ('ESTUDIO', 'Examen / Estudio'), ('MUDANZA', 'Mudanza'), ('MATRIMONIO', 'Matrimonio'), ('NACIMIENTO', 'Nacimiento / Paternidad'), ('OTRA', 'Otra Causa')], max_length=20)),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de Fin')),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de Revisión'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=10)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licencias', to='core.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('REMOTO', '🏠 Trabajo Remoto'), ('TRAMITE', '🏦 Trámite Personal / Salida Anticipada'), ('COMPENSATORIO', '⏱️ Franco Compensatorio'), ('OTRO', '📝 Otro Motivo')], default='REMOTO', max_length=20)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('motivo', models.TextField(blank=True, help_text='Detallar brevemente (opcional)', null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=10)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permisos', to='core.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudVacaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_solicitud', models.DateField(auto_now_add=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('dias_totales', models.IntegerField(editable=False)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('solo_habiles', models.BooleanField(default=False, help_text='Si se marca, el sistema NO descontará fines de semana ni feriados.', verbose_name='¿Contar solo días hábiles?')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='APROBADO', max_length=20)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='core.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='ConsumoDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias_descontados', models.IntegerField()),
                ('bolsa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='core.bolsavacaciones')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='core.solicitudvacaciones')),
            ],
        ),
    ]
