# Generated by Django 5.2.12 on 2026-03-18 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='licencia',
            name='fecha_solicitud',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='permiso',
            name='fecha_solicitud',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
